### ISSUE TITLE
SDR# locks up and freezes

### ISSUE THREAD

**Issue by creinemann** [JVital2013/goesrecv-ps#1]
First, great work, I got it up and running in under a minute.
But, if I stop SDR# first, It freezes and I have to do a CTRL ALT DEL to get out of it.  Both on SDR sharp ver 1832, and older version 1702.

If I stop goesrecv-rtltcp.ps1 first, then I am able then to stop SDR# and exit out of it just fine.

Running goestools on a PI, and then SDR# on a windows 11 PC
Carl
usradioguy.com

**Comment by JVital2013** [comment]
Strange, I haven't had that experience. I don't have Windows 11 but I can spin up a test machine to test this case - it might be the problem.

Just some clarifying questions to help me get to the bottom of it:

- Are you stopping SDR# with the stop button, and not just closing the program?
- Can you use "real" rtl_tcp server with SDR# without this issue? It's fine if you don't know/can't test it
- Which computer is running goesrecv-rtltcp.ps1? I assume it's one the same machine as SDR#

Thanks for the feedback,
-Jamie

**Comment by creinemann** [comment]
_Are you stopping SDR# with the stop button, and not just closing the program?_
Yes, If I click the stop button then SDR# freezes and goesrecv-rtltcp.ps1 stops and closes.
If I run it again, but close SDR# then both programs close just fine.

_Can you use "real" rtl_tcp server with SDR# without this issue? It's fine if you don't know/can't test it_
I have an rtl-tcp server running on a pi set up for ADSB and I can access it and hit stop and then resume it just fine. No lock up. (different ports though)

_Which computer is running goesrecv-rtltcp.ps1? I assume it's one the same machine as SDR#_
goesrecv-rtltcp.ps1 and SDR# are both running on the same windows machine, with goestools running on a pi.

If I terminate goesrecv-rtltcp.ps1 first, then SDR# loses the TCP connection as expected, but continues to function

CPU usage for SDR# is about 8-9% and is .1% while running for Hope it helps!

**Comment by JVital2013** [comment]
I was able to reproduce the issue by moving to another SDR# version - I was on 1830 and it worked fine, but who knows why. It crashes for me on other versions.

Can you try the latest commit? For me it fixes the issue on versions of SDR# that crash

**Comment by creinemann** [comment]
Seems to be working on SDR#1700's versions and on SDR# 1832.
Thanks
